version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nexus-postgres
    environment:
      POSTGRES_DB: nexus_ai
      POSTGRES_USER: nexus_admin
      POSTGRES_PASSWORD: SecurePassword123!
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./nexus/src/main/resources/database-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - nexus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus_admin -d nexus_ai"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: nexus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - nexus-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  influxdb:
    image: influxdb:2.7
    container_name: nexus-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: SecurePassword123!
      DOCKER_INFLUXDB_INIT_ORG: nexus-ai
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin-token
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - nexus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nexus Application
  nexus-app:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    container_name: nexus-application
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: nexus_ai
      DB_USER: nexus_admin
      DB_PASSWORD: SecurePassword123!
      REDIS_HOST: redis
      REDIS_PORT: 6379
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: admin-token
      INFLUXDB_ORG: nexus-ai
      INFLUXDB_BUCKET: metrics
    ports:
      - "8094:8094"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    networks:
      - nexus-network
    restart: unless-stopped

  # Grafana for monitoring
  grafana:
    image: grafana/grafana:10.0.0
    container_name: nexus-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - nexus-network
    depends_on:
      - influxdb

volumes:
  postgres_data:
  redis_data:
  influxdb_data:
  influxdb_config:
  grafana_data:

networks:
  nexus-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16