services:
  postgres:
    image: postgres:15
    container_name: nexus-postgres
    environment:
      POSTGRES_DB: nexus_ai
      POSTGRES_USER: nexus_admin
      POSTGRES_PASSWORD: SecurePassword123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nexus-network

  redis:
    image: redis:7-alpine
    container_name: nexus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - nexus-network

  influxdb:
    image: influxdb:2.0
    container_name: nexus-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: SecurePassword123!
      DOCKER_INFLUXDB_INIT_ORG: nexus-ai
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - nexus-network

volumes:
  postgres_data:
  redis_data:
  influxdb_data:

networks:
  nexus-network:
    driver: bridge