global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # NEXUS AI Backend Monitoring
  - job_name: 'nexus-backend'
    static_configs:
      - targets: ['nexus-backend:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # NEXUS AI Frontend Monitoring
  - job_name: 'nexus-frontend'
    static_configs:
      - targets: ['nexus-frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL Database Monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis Cache Monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Nginx Proxy Monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']